# Pytorch Fundamentals

In [51]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu124


# Introduction to tensors

In [52]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)


cuda


Creating Tensors

In [53]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [54]:
# Back as python int
scalar.item()

7

In [55]:
vector=torch.tensor([7,7])
vector,vector.ndim,vector.shape

(tensor([7, 7]), 1, torch.Size([2]))

In [56]:
#Matrix
Matrix=torch.tensor([[7,8],[9,3]])

In [57]:
Tensor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
Tensor.ndim,Tensor.shape,Tensor[0]

(3,
 torch.Size([1, 3, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [58]:
# Random Tensors
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [59]:
# Create random tensor similar to image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [60]:
zeros=torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [61]:
ones=torch.ones((3,5))
ones,ones.dtype

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 torch.float32)

Range of tensors and tensors like

In [62]:
# torch range
bw_1_10=torch.arange(0,1000,step=90)
bw_1_10

tensor([  0,  90, 180, 270, 360, 450, 540, 630, 720, 810, 900, 990])

In [63]:
# creating tensors like
ten_zeros=torch.zeros_like(bw_1_10)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
# float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor.dtype

torch.float32

In [65]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [66]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [67]:
float_32_tensor*8

tensor([24., 48., 72.])

In [68]:
some_tensor=torch.rand(3,4)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype: torch.float32
Shape: torch.Size([3, 4])
Device tensor is on: cpu


Manupulating Tensors

In [69]:

# ! Does it element wise
tensor=torch.tensor([1,2,3])
# tensor+=10
tensor

tensor([1, 2, 3])

Matrix Multiplication

In [70]:

# ! Multiplication takes place like matrix and follows column and row formula and follows matrix rules
# ^ Normal
print(tensor,'*',tensor)
print(f"Equals {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [71]:

# ^ Matrix
# todo 1*1+2*2+3*3
torch.matmul(tensor,tensor)

tensor(14)

In [72]:
%%time
value=0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


In [73]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [74]:
# Shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
tensor_B=torch.tensor([[7,10],
                      [8,11],
                      [9,12]])
# * Same as matmul
# torch.mm(tensor_A,tensor_B)
#? wont work
#^ transpose
tensor_B=torch.transpose(tensor_B,0,1)
tensor_A.shape,tensor_B.shape
torch.mm(tensor_A,tensor_B)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Tensor Aggregation

In [75]:
x=torch.arange(0,100,10)
# *min
print(torch.min(x))
# *max
print(torch.max(x))
# *mean
# todo make datatype as req
print(torch.mean(x.type(torch.float32)))



tensor(0)
tensor(90)
tensor(45.)


Possitional

In [76]:
x.argmin(),x.argmax()

(tensor(0), tensor(9))

Reshaping Stacking Squeezing and Unsqueezing Tensors

In [77]:
x=torch.arange(1.,10.)
# ! Reshaping - Changing the dimenssion of the tensor
reshaped=x.reshape(3,3,1)
reshaped

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]])

In [78]:

# ! Squeeze and unsqueezde - add or remove 1 dimenssion from the tensor
y=reshaped.squeeze()
# * dim takes the place to add the new dim
z=y.unsqueeze(dim=2)
y.shape,reshaped.shape,z.shape


(torch.Size([3, 3]), torch.Size([3, 3, 1]), torch.Size([3, 3, 1]))

In [79]:

# ! View - returns  a view of an input tensor of certain shape but keep the same memory as the orignal tensor
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [80]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [81]:

# ! Stacking - Combining multiple tensors on top of each other (vstack) os side by side (hstack)
# *dim changes the type
# ? 0 and 1 for vstack and hstack
x_stack=torch.stack([x,x,x,x],dim=1)
x_stack

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [82]:

# ! Permuted - return a view of the input with dimenssions (swapped) in a certain way
x_orignal=torch.rand(size=(224,224,3))
# todo 0>1 1>2 2>0
x_permute=x_orignal.permute(2,0,1)
x_orignal.shape,x_permute.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [83]:

# ? Gives a view of same data 
x_orignal[0,0,0]=10
x_orignal[0,0,0],x_permute[0,0,0]

(tensor(10.), tensor(10.))

# Indexing

In [84]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [85]:
x[0],x[0][0],x[0,0,0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [86]:
# all value of 0 n 1 dim and only index 1 of 2
x[:,:,1]

tensor([[2, 5, 8]])

In [87]:
# all value of 0 dim and only index 1 of 2 n 1
x[:,1,1]

tensor([5])

In [88]:
# all value of 2 dim and only index 1 of 0 n 1
x[0,1,:]

tensor([4, 5, 6])

In [89]:
# get 9
x[0,2,2]

tensor(9)

In [90]:
import numpy as np
array=np.arange(1.0,9.0)
tensor=torch.from_numpy(array)
# ! does not automatically change here
array,tensor,array.dtype,tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 dtype('float64'),
 torch.float64)

In [91]:
array+=1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [92]:
tensor=torch.ones(7)
array=tensor.numpy()
tensor,array,tensor.dtype,array.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 torch.float32,
 dtype('float32'))

# Reproducability (trying to take random out of random)

In [93]:

#! reduce randomness -> random seed 
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor==random_tensor_B)

tensor([[0.5888, 0.8403, 0.4761, 0.7140],
        [0.4644, 0.6362, 0.8892, 0.1317],
        [0.7164, 0.2706, 0.6560, 0.6614]])
tensor([[0.3648, 0.1490, 0.8693, 0.0294],
        [0.5449, 0.0794, 0.2313, 0.2927],
        [0.3386, 0.3708, 0.0831, 0.0944]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [94]:

# * set seed

torch.manual_seed(42)
random_tensor_A=torch.rand(3,4)
torch.manual_seed(42)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)

print(random_tensor_B)

print(random_tensor_A==random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# GPU

In [95]:
! nvidia-smi

Thu Aug  8 23:34:19 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.61                 Driver Version: 551.61         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8              1W /  126W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

check gpu

In [96]:
import torch 
torch.cuda.is_available()

True

In [97]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [105]:
tensor_to_gpu=tensor.to(device)
tensor_to_gpu.device

device(type='cuda', index=0)

In [107]:
tensor_back_on_cpu=tensor_to_gpu.cpu()

tensor_back_on_cpu.device

device(type='cpu')